// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oaockrwpzfamwrkzpapb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hb2NrcndwemZhbXdya3pwYXBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTI5NTYsImV4cCI6MjA1OTc4ODk1Nn0.07c9GOURkVguhAFBuQQSyRRAiNP-W3CrFjzcZZSlDdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);